**Conceitos básicos com OpenCV**

Lendo uma imagem de um diretório: 

In [3]:
import numpy as np
import cv2
#from google.colab.patches import cv2_imshow
#cv2_imshow(img)


In [51]:
def cv2_imshow(img):
    cv2.imshow('', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [26]:
img = cv2.imread('avatar.png',0)

Exibindo uma imagem

In [52]:
#implementei um método para fazer o mesmo que o cv2_imshow do google.colab
cv2_imshow(img)

Salvando uma imagem em disco

In [28]:
cv2.imwrite('avatar_gray.png',img)

True



---


**Operações básicas: modificando o valor de um pixel**

Uma imagem é uma matriz. No OpenCV, cada pixel (posição da matriz) de uma imagem colorida está no formato BGR (Blue, Green, Red). Execute o código e veja a saída na tela. 

Uma imagem é uma matriz. No OpenCV, cada pixel (posição da matriz) de uma imagem colorida está no formato BGR (Blue, Green, Red). Execute o código e veja a saída na tela. 

In [29]:
# carregando a imagem em BGR
img = cv2.imread('avatar.png')

px = img[50,50]
print(px)

[ 99 107 107]


Acessando apenas o canal “blue” do pixel

In [30]:
blue = img[50,50, 0]
print(blue)

99


Acessando apenas o canal “red” do pixel

In [31]:
red = img[50,50, 2]
print(red)

107


Modificando o valor de um único pixel

In [32]:
img[50,50] = [255, 255, 255]
print(img[50,50])

[255 255 255]


Forma otimizada de acessar pixel de uma imagem usando numpy

In [33]:
red = img.item(50,50,2)
print(red)

255


Modificando a intensidade do canal Red do pixel usando numpy


In [37]:
img.itemset((50,50,2),100)
red = img.item(50,50,2)
print(red)

100


Retornando uma tupla de linha, coluna e número de canais de cores da imagem

In [34]:
print(img.shape)

(168, 160, 3)


Retorna o número de pixel

In [35]:
print(img.size)

80640


Imprimindo apenas o canal Red


In [38]:
b,g,r = cv2.split(img)
print(g)

[[247 247 247 ... 247 247 247]
 [247 247 247 ... 247 247 247]
 [247 247 247 ... 247 247 247]
 ...
 [ 82  74  74 ...   8   8   8]
 [ 82  82  82 ...   8   8   8]
 [ 99  82  82 ...   8   8   8]]


Modificando apenas o canal Red para 0

In [40]:
img[:,:,2] = 0
cv2.imwrite("avatar_red.png", img)

True

In [53]:
img_red = cv2.imread("avatar_red.png")
cv2_imshow(img_red)

Rotacionando a imagem em 180 graus

In [46]:
import imutils

In [47]:
# rotate image 180° 
rotated = imutils.rotate(img, 180)
cv2_imshow(rotated)

Redimensionando a imagem

In [45]:
resized = cv2.resize(img, (800, 800), interpolation=cv2.INTER_CUBIC)
cv2_imshow(resized)

**Funções de desenho**

Desenhando uma linha

Para desenhar uma linha, você precisa passar as coordenadas inicial e final da linha. 

Criando uma imagem preta e desenhando uma linha azul nos cantos superior esquerdo e inferior direito.

In [54]:
# Create a black image
img = np.zeros((512,512,3), np.uint8)

# Draw a diagonal blue line with thickness of 5 px
img = cv2.line(img,(0,0),(511,511),(255,0,0),5)

cv2_imshow(img)

Desenhando um retângulo

Especificamos o canto superior esquerdo e o canto inferior direito do retângulo. 

In [55]:
img = cv2.rectangle(img,(384,0),(510,128),(0,255,0),3)
cv2_imshow(img)

**Adicionado texto em uma imagem**

In [56]:
# Create a black image
img = np.zeros((512,512,3), np.uint8)

font = cv2.FONT_HERSHEY_DUPLEX
cv2.putText(img,'OpenCV',(10,500), font, 4,(255,255,255),2,cv2.LINE_AA)

cv2_imshow(img)

**Trabalhando com vídes**

Abrindo um vídeo de um arquivo

In [57]:
import os
import os.path

In [58]:
frames_dir = "frame_dir/"

if not os.path.exists(frames_dir):
    os.makedirs(frames_dir)  

In [59]:
cap = cv2.VideoCapture('teste.mp4')

# frame id
id_frame = 0

while(cap.isOpened()):
    ret, frame = cap.read()

    if ret:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        frame_path = os.path.join(frames_dir, str(id_frame) + ".png")

        # salva a imagem (frame) no disco
        cv2.imwrite(frame_path, gray)

        id_frame += 1
    
cap.release()

**Referências**

[OpenCV-Python Tutorials](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_tutorials.html)